
app.lang = {}

app.lang.supportedLanguageList = [
  'en-us'
  'bn-bd'
]

app.lang.defaultLanguage = null
app.lang.defaultLanguageIndex = 0

app.lang.loadDefaultLanguage = ->
  app.lang.defaultLanguage = (lib.localStorage.getItem 'app-lang-default-language') or 'en-us'
  app.lang.defaultLanguageIndex = app.lang.supportedLanguageList.indexOf(app.lang.defaultLanguage)

app.lang.loadDefaultLanguage()

app.lang.saveDefaultLanguage = ->
  lib.localStorage.setItem 'app-lang-default-language', app.lang.defaultLanguage
  app.lang.defaultLanguageIndex = app.lang.supportedLanguageList.indexOf(app.lang.defaultLanguage)

app.lang.phrases = 
  'bn-bd':
    'new patients':'নতুন রুগী'
    'new records':'নতুন রেকর্ড'
    'view':'বিস্তারিত দেখুন'
    'total patients':'মোট রুগী'
    'total records':'মোট রেকর্ড'
    'unpaid invoices':'অপরিশোধিত ইনভয়েস'
    'days left':'দিন বাকি'
    'renew':'নবায়ন করুন'
    'purchase':'ক্রয় করুন'
    'Add Medicine':'ঔষধ যোগ করুন'
    'Add Blood Pressure':'রক্ত চাপ যোগ করুন'
    'Add Heart Rate':'নাড়ীর গতি যোগ করুন'
    'Add Respiratory':'শ্বাসের হার যোগ করুন'
    'Add Oxygen Saturation':'(রক্তে দ্রবীভূত) অক্সিজেনের মাত্রা যোগ করুন'
    'Add Temperature':'তাপমাত্রা যোগ করুন'
    'Add Blood Sugar': 'রক্তে চিনির পরিমাণ যোগ করুন'
    'Medicine Name':'ঔষধের নাম'
    'Manufacturer':'প্রস্তুতকারী'
    'Manufacturer Name': 'প্রস্তুতকারীর নাম'
    'Brand Name': 'ঔষধের নাম'
    'Form':'প্রকার'
    'Generic Name':'ঔষধের পুস্তকে উল্লেখিত নাম '
    'Start Date':'শুরুর দিন '
    'Tablet':'ট্যাবলেট '
    'Capsule': 'ক্যাপসুল'
    'Injection':'ইঞ্জেকশন'
    'Syrup':'সিরাপ '
    'Suspension':'সাস্পেনশান '
    'I.V injection':'শিরায় দেওয়ার ইনজেকশন'
    'I.V Injection':'শিরায় দেওয়ার ইনজেকশন'
    'I.M injection':'মাংসে দেওয়ার ইনজেকশন'
    'PR (Per Rectal)':'পায়ু পথে প্রদেয় '
    'p.r (per rectal)':'পায়ু পথে প্রদেয় '
    's/c injection':'ত্বকের নীচে দেওয়ার ইনজেকশন'
    'S/C Injection':'ত্বকের নীচে দেওয়ার ইনজেকশন'
    'Topical application ear': 'কানে দেয়ার জন্য'
    'Topical application eye': 'চোখে দেয়ার জন্য'
    'topical application ear': 'কানে দেয়ার জন্য'
    'Topical application eye': 'চোখে দেয়ার জন্য'
    'Times per':'ব্যবহারের সংখ্যা '
    'Interval in hours':'মধ্যবর্তী বিরতির সময় (ঘণ্টায়)'
    'Hour': 'ঘণ্টা'
    'Quantity Per Fill':'প্রতি প্রেস্ক্রিপশানে দেওয়া ঔষধের সংখ্যা '
    'Number of Refill':'পরবর্তীতে ক্রয়যোগ্য '
    'Ends on':'শেষের সময় '
    'Direction':'ঔষধ গ্রহণের নির্দেশনা '
    'Anytime':'যে কোনো সময়'
    'Not Related With Meal': 'খাবারের আগে পরে যে কোনো সময়'
    'After Meal':'খাবারের পরে'
    'Before Meal':'খাবারের আগে '
    'Full Stomach':'ভরা পেটে'
    'Empty Stomach':'খালি পেটে'
    'Comments':'মন্তব্য '
    'Save':'সংরক্ষণ করুন '
    'My Medication': 'ঔষধপত্র'
    'My Vitals': 'আবশ্যিক পরিমাপ'
    'My Tests':'পরীক্ষা সমূহ '
    'My Test Results':'পরীক্ষা সমূহ '
    'Other Tests': ''
    'Blood Pressure':'রক্ত চাপ'
    'Heart Rate':'নাড়ীর গতি'
    'Blood Sugar':'রক্তে চিনির পরিমাণ '
    'BMI':'বিএমআই(উচ্চতা সাপেক্ষে ওজন)'
    'Add Vital':'আবশ্যিক পরিমাপ  যোগ '
    'Systolic':'রক্তচাপ (উপর)'
    'Diastolic':'রক্তচাপ (নীচ)'
    'Random':'যে কোনো সময়ে '
    'mm Hg':'মিমি মার্কারি'
    'CLEAR':'তথ্য মুছে ফেলুন'
    'Clear':'তথ্য মুছে ফেলুন'
    'ADD':'যোগ করুন '
    'Add':'যোগ করুন '
    'Delete':'তথ্য মুছে ফেলুন'
    'Prev':'পূর্ববর্তী '
    'Next':'পরবর্তী '
    'bpm':'প্রতি মিনিটে হার '
    'Before Meal (Fasting)':'সকালে খাদ্য গ্রহণের আগে  '
    'After Meal (2 hour)':'খাদ্য গ্রহণের ২ ঘণ্টা পরে'
    'Unit':'একক'
    'mmol/L':'মিলিমোল/প্রতি লিটারে'
    'mg/dl':'মিলিগ্রাম প্রতি ১০০ মিলি লিটারে'
    'Height':'উচ্চতা'
    'Weight':'ওজন'
    'My Visits & Report':'চিকিৎসক সাক্ষাত ও রিপোর্ট সমুহ'
    'Visit history':'সাক্ষাতের ইতিহাস'
    'My Demography':'পরিচিতি ও অবস্থান'
    'My Visits':'সাক্ষাৎ সমূহ'
    'Date':'তারিখ'
    'Hospital':'হাসপাতালের নাম'
    'Clinic':'ক্লিনিকের নাম'
    'Name of Doctor':'চিকিৎসকের নাম'
    'Speciality':'যে বিষয়ে বিশেষজ্ঞ '
    'Report Type':'রিপোর্টের ধরণ'
    'Prescription':'প্রস্তাবিত চিকিৎসা'
    'Blood Report':'রক্ত পরীক্ষার ফল'
    'Operation Note':'শল্য চিকিৎসার নথি'
    'Assessment':'স্বাস্থ্য মূল্যায়ন'
    'Urine report':'প্রস্রাব পরীক্ষার নথি '
    'Stool Report':'মল পরীক্ষার নথি '
    'C/S':'জীবাণু সংবেদনশীলতা পরীক্ষা '
    'Culture and Sensitivity':'জীবাণু সংবেদনশীলতা পরীক্ষা'
    'Biopsy Report':'বায়প্সি ফলাফল '
    'Histopathology Report':'হিস্টোপ্যাথলজি পরীক্ষার ফল'
    'Basic Details':'নুন্যতম বর্ণনা '
    'Address Details':'ঠিকানার বিবরণ '
    'Details': 'বর্ণনা'
    'Detail': 'বর্ণনা'
    'Name':'নাম'
    'Age':'বয়স'
    'Sex':'লিঙ্গ'
    'Blood Group':'রক্তের গ্রুপ'
    'Address':'ঠিকানা '
    'Email':'ইমেইল '
    'Present Address':'বর্তমান ঠিকানা '
    'Permanent Address':'স্থায়ী ঠিকানা '
    'Next of Kin':'নিকটাত্মীয় '
    'times':'বার'
    'Current Medication': 'চলতি ঔষধপত্র'
    'Stopped Medication': 'পুরাতন ঔষধপত্র'
    'Every': 'প্রতি'
    'Days': 'দিন'
    'Every Day': 'প্রতিদিন'
    'Temperature': 'তাপমাত্রা'
    'Result': 'ফলাফল'
    'Other Tests': 'অন্যান্য পরীক্ষা'
    'Patient Notes': ''
    'Dose': 'ডোজ'
    'Route': 'পথ'
    'Strength': 'শক্তি'
    'Respiratory Rate': 'শ্বাসের হার'
    'Oxygen Saturation': '(রক্তে দ্রবীভূত) অক্সিজেনের মাত্রা'
    'Allergy': 'এলারজি'
    'Next of Kin': 'নিকটাত্মীয়'
    'Remind Me To Take This Medicine': 'এই ওষুধটি নিতে মনে করিয়ে দিবেন'
    'First Dose': 'প্রথম নেয়া হয়েছে'
    'Last Dose': 'শেষ নেয়া হয়েছে'
    'Next Dose': 'পরবর্তী নেয়া হবে'
    'Dose(s) Left': 'নেয়া বাকি আছে'
    'Take Medication': 'ওষুধ নিন'
    'No Data added yet': 'এখনো কোন তথ্য যোগ করা হয়নি'
    'Solution': 'সলিউশান (তরল)'
    'Ointment': 'অয়েন্টমেন্ট'
    'Cream': 'ক্রিম'
    'Skin Patch': 'ত্বকে ব্যবহার্য তালি (ঔষধ)'
    'S/L': 'জিহ্বার নীচে ব্যবহার্য '
    'S/C': 'ত্বকের নীচে'
    'Nebulizer': 'নেবুলাইযার ( নেবুলাইযার মেশিনে ব্যবহৃত তরল)'
    'Inhaler': 'শ্বাসের সাথে গ্রহণযোগ্য'
    'Topical application skin': 'ত্বকের উপরে প্রদেয়'
    'Topical application ear': 'কানে প্রদেয়'
    'Topical application eye': 'চোখে প্রদেয়'
    'Intravaginal': 'যোনী পথে প্রদেয়'
    'Transdermal': 'ত্বকে প্রদেয়'
    'Oral': 'মুখে খাওয়া'
    'p.o': 'মুখে খাওয়া'
    'P.O': 'মুখে খাওয়া'
    'Suppository': 'সাপোজিটার (পায়ু বা যোনী পথে প্রদেয় ঔষধি শলাকা)'
    'As Needed': 'ওষুধ চলবে'
    'kgs':'কেজি'
    'kg':'কেজি'
    'lbs':'পাউন্ড'
    'cm':'সেমি'
    'metre': 'মিটার'
    'ft/inch': 'ফিট/ইঞ্চ'
    'Ft': 'ফিট'
    'Inch': 'ইঞ্চ'
    'stone-lbs': ''
    'Normal': 'সাধারণ'
    'rpm': 'প্রতি মিনিটে হার'
    'bpm':'প্রতি মিনিটে হার'
    '°C': 'সেলসিয়াস'
    '°F': 'ফারেনহাইট'
    'Birth Date': 'জন্ম তারিখ'
    'Address Details': 'ঠিকানার বিবরণ'
    'Emergency Contact': 'জরুরী যোগাযোগ'
    'Relation':'সম্পর্ক'
    'Contact Number': 'যোগাযোগের নম্বর'
    'Physical Address': 'ঠিকানা'
    'Calculate': 'গণনা করুন'
    'Male':'পুরুষ'
    'Female':'মহিলা'
    'Other':'অন্যান্য'
    'Dashboard': 'মূল পাতা'
    'Institution': 'প্রতিষ্ঠান'
    'BMDC Lookup': 'চিকিৎসকের সত্যতা যাচাই করুন'
    'Like Us': 'ফেসবুকে লাইক করুন'
    'My Next Visit': 'পরবর্তী সাক্ষাত'
    'Doctor-Patient Notes': 'রোগীর নথি'
    'Help': 'সাহায্য'
    'FAQ': 'প্রশ্নোত্তর'
    'Patient Gallery': 'ছবি/ভিডিও গ্যালারি'
    'Weeks': 'সপ্তাহ'
    'Week': 'সপ্তাহ'
    'Welcome': 'স্বাগতম'
    'Logout': 'লগ আউট'
    'Morning': 'সকাল'
    'Noon': 'দুপুর'
    'Night': 'রাত'
    'for': 'করে'
    'Discharge Reason': 'ছাড়পত্র প্রদানের কারণ'
    'Save Advised Admission': 'সেভ করুন'
    'Advised Test': 'উপদেশকৃত পরিক্ষাসমুহ'
    'Category': 'ক্যাটেগরি'
    'Symptoms': 'উপসর্গ/ইতিহাস'
    'Note(s)': 'নথি'
    'Next Visit': 'পরবর্তী সাক্ষাত'
    'Vitals': 'আবশ্যিক পরিমাপ'
    'Vital': 'আবশ্যিক পরিমাপ'
    'Discharge Note':'ছাড়পত্র'
    'Diagnosis':'নির্ণীত রোগের নামসমূহ'
    'Notes':'নথি'
    'Name of Doctor':'চিকিৎসকের নাম'
    'Name of the Doctor':'চিকিৎসকের নাম'
    'Out patient':'বর্হিবিভাগ'
    'Discharged with advise':'উপদেশ সহ ছাড়পত্র'
    'Advised admission':'হাসপাতালে ভর্তির উপদেশ'
    'Seen in emergency':'জরুরি বিভাগে সাক্ষাৎ'
    'Admission to':'ভর্তির বিবরণ'
    'Type':'প্রকার'
    'Vacant':'খালি' 
    'Search':'অনুসন্ধান'
    'Patient Log':'পেশেন্ট লগ'
    'ONLINE SEARCH':'অনলাইনে অনুসন্ধান'
    'OFFLINE SEARCH':'অফলাইনে অনুসন্ধান'
    'LIST ALL IMPORTED/OFFLINE PATIENTS':'সব আমদানিকৃত/অফলাইন পেসেন্টের তালিকা'
    'Results':'ফলাফলসমূহ'
    'BP':'রক্তচাপ'
    'HR':'হৃদ কম্পন'
    'Temp':'তাপমাত্রা'
    'Visit Details Heading':'সাক্ষাৎ বিবরণ এর শিরোনাম'
    'Prescription':'প্রেসক্রিপশন'
    'Admission Date':'ভর্তির তারিখ'
    'Department':'বিভাগ'
    'Current Medicine':'বর্তমান ঔষুধ'
    'Add Medicine':'মেডিসিন যোগ করুন'
    'RR':'শ্বাসের হার'
    'SpO2':'রক্তে দ্রবীভূত অক্সিজেনের মাত্রা'
    'Investigation':'তদন্ত'
    'Test':'পরীক্ষা'
    'Day':'দিন'
    'Select Duration':'কতদিন পর দেখা করবেন'
    'Select Priority':'অগ্রাধিকার নির্বাচন করুন'
    'Write a Private Note':'ব্যাক্তিগত নথি লিখুন'
    'Show Advanced':'আরো কিছু বিকল্প দেখুন'
    'Dose Timing e.g 1+1+1':'ঔষুধ খাওয়ার সময়সমূহ (উদাঃ ১ + ১ + ১)'
    'Dose Timing':'ঔষুধ খাওয়ার সময়সমূহ'
    'Continue As Needed':'প্রয়োজন অনুযায়ী চালিয়ে যান'
    'Add':'যোগ করুন'
    'Favorite':'পছন্দ/পছন্দসমূহ'
    'Add + Favorite':'যোগ করুন এবং পছন্দে রাখুন'
    'Favorite Medicine':'পছন্দকৃত ঔষুধসমূহ'
    '-- empty --':'-- খালি --'
    'Preview':'পূর্বরূপ'
    'Visit':'পরিদর্শন'
    'Patient Stay':'ভর্তি তথ্য'
    'Invoice':'চালান'
    'Patient Name':'রোগীর নাম'
    'Temperature in Celsius': 'তাপমাত্রা (সেলসিয়াস)'
    'Temperature in Fahrenheit': 'তাপমাত্রা (ফারেনহাইট)'
    'Service':'সেবা'
    'Billed':'বিল'
    'Paid':'পরিশোধ করেছে'
    'Edit':'সম্পাদন করুন'
    'History & Physical':'পূর্ণাঙ ইতিহাস'
    'Record Title':'রেকর্ড শিরোনাম'
    'Add Symptoms':'উপসর্গ/ইতিহাস যোগ করুন'
    'Examination':'পরীক্ষা'
    'Add Examination':'পরীক্ষা যোগ করুন'
    'Select Vital Types':'আবশ্যিক পরিমাপ প্রকার নির্বাচন করুন'
    'Add Diagnosis':'নির্ণীত রোগের নামসমূহ যোগ করুন'
    'Advise/Note':'উপদেশ/নথি'
    'Add Advise/Note':'উপদেশ/নথি যোগ করুন'
    'Add Investigation':'তদন্ত যোগ করুন'
    'Priority':'অগ্রাধিকার'
    'Select Priority':'অগ্রাধিকার নির্বাচন করুন'
    'Select Date':'তারিখ চয়ন করুন'
    'Add New':'নতুন ঔষুধ যোগ করুন'
    'Search with Patient Name, phone, Email, NID or Hospital Number':'পেসেন্ট এর নাম, ফোন, ইমেইল, এন আই ডি অথবা হসপিটাল নাম্বার দিয়ে অনুসন্ধান করুন'
    'Patient(s) found':'রোগী (সমূহ) পাওয়া গেছে'
    'imported':'আমদানিকৃত'
    'View Patient':'রোগী দেখুন'
    'New Prescription':'নতুন প্রেসক্রিপশন'
    'Patient Serial':'রোগীর সিরিয়াল'
    'Patient Name':'রোগীর নাম'
    'Sex':'লিঙ্গ'
    'Suggested Institution':'প্রস্তাবিত প্রতিষ্ঠান'
    'Doctor Advised/Notes':'ডাক্তার এর পরামর্শ/নথি '
    'Prepared by':'প্রস্তুতকারক'
    'Finish':'সমাপ্তি'
    'Print':'প্রিন্ট'
    'New Visit':'নতুন পরিদর্শন'
    'Examination':'পরীক্ষা'
    'add as favorite':'পছন্দে যোগ করুন'
    'favorite list':'পছন্দসমূহের লিস্ট'
    'New Diagnosis':'নতুন নির্ণীত রোগের নামসমূহ'
    'Note/Advised':'নথি/পরামর্শ'
    'Next Visit Date':'পরর্বতী পরিদর্শন তারিখ'
    'Add Priority':'অগ্রাধিকার যোগ করুন'
    'Patient Current Medicine':'রোগির বর্তমান ঔষধ'
    'New Medicine':'নতুন ঔষধ'
    'Favorite(s)':'পছন্দসমুহ'
    'Insulin':'ইন্সুলিন'
    'Continue':'চলবে'
    'Stop':'স্থগিত'
    'Stopped':'স্থগিত'
    'Choose an option':'একটি অপশন নির্বাচন করুন'
    '-- no data available --':'তথ্য আয়ত্তাধীন নাই'
    'Dose Administer Timing e.g 1+1+1':'ডোজ দেয়ার সময়সমূহ (যেমন ১+১+১)'
    'Advice':'উপদেশ'
    'Referred By':'উপদেশকারী চিকিৎসক'
    'Admitted By':'ভর্তির আদেশদানকারী চিকিৎসক'
    'Clinic/Hospital':'ক্লিনিক/হাসপাতাল'
    'By': 'দ্বারা'
    'Search and Book A Doctor':'চিকিৎসক অনুসন্ধান ও বুকিং'
    'Search By Organization' : 'প্রতিষ্ঠানের নাম দিয়ে অনুসন্ধান করুন'
    'Short Code of Doctor (If Known)' : 'ডাক্তারের কোড (যদি জানা থাকে)'
    'Location/Address' : 'ঠিকানা'
    'Degree' : 'ডিগ্রী'
    'Select a Booking Date' : 'বুকিং তারিখ প্রদান করুন'
    'Select Department':'বিভাগ নির্বাচন করুন'
    'Search Results':'অনুসন্ধানের ফলাফল'
    'No results':'কোন ফলাফল পাওয়া যায়নি'
    'Organization Name': 'প্রতিষ্ঠানের নাম'
    'Cancel': 'না'
    'Confirm': 'হ্যাঁ'
    'OK': 'ঠিক আছে'
    'City':'শহর'
    'Degrees':'ডিগ্রী'
    'Experience':'অভিজ্ঞতা'
    'New Patient Fee':'নতুন রোগীর ফি'
    'Old Patient Fee':'পুরাতন রোগীর ফি'
    'Select Time Slot':'সময়ের স্লট নির্বাচন করুন'
    'You already have a booking here':'আপনার ইতিমধ্যে এখানে একটি বুকিং আছে'
    'Book and Pay from wallet':'বুকিং দিন এবং ওয়ালেট থেকে পরিশোধ করুন'
    'Specializations':'বিশেষজ্ঞ'
    'Select Booking Date and Slot': 'বুকিংয়ের তারিখ এবং স্লট নির্বাচন করুন'
    'Bangabandhu Sheikh Mujib Medical University (BSMMU)' : 'বঙ্গবন্ধু শেখ মুজিব মেডিকেল বিশ্ববিদ্যালয় (বিএসএমএমইউ)'
    'Cardiology':'কার্ডিওলজি'
    'Dermatology & Venereology':'চর্ম ও যৌন'
    'Dermatology & Venerology':'চর্ম ও যৌন'
    'Endocrinology & Metabolism':'এন্ডোক্রিনলজি ও মেটাবলিজম - হরমোন সংক্রান্ত'
    'Gastroenterology':'গ্যাস্ট্রোএন্টারোলজি - পরিপাকতন্ত্র'
    'Hematology':'হেমাটোলজি - রক্ত সংক্রান্ত'
    'Hepatology':'হেপাটোলজি - লিভার সংক্রান্ত'
    'Internal Medicine':'ইন্টারনাল মেডিসিন'
    'Neonatology':'নবজাতক'
    'Nephrology':'নেফ্রোলজি - কিডনি সংক্রান্ত'
    'Neurology':'নিউরোলজি - স্নায়ু সংক্রান্ত'
    'Oncology':'অনকোলজি - ক্যান্সার সংক্রান্ত'
    'Paediatrics':'শিশুরোগ'
    'Paediatric Gastroenterology':'পেডিয়াট্রিক গ্যাস্ট্রোএন্টারোলজি - শিশু পরিপাকতন্ত্র সংক্রান্ত'
    'Paediatric Haematology & Oncology':'পেডিয়াট্রিক হেমাটোলজি ও অনকোলজি - শিশু রক্ত  ও ক্যান্সার সংক্রান্ত'
    'Paediatric Nephrology':'পেডিয়াট্রিক নেফ্রোলজি - শিশু কিডনি সংক্রান্ত'
    'Physical Medicine & Rehabilitation':'ফিজিক্যাল মেডিসিন ও রিহ্যাবিলিটেশন'
    'Psychiatry':'মনোরোগবিদ্যা'
    'Rheumatology':'রিউম্যাটোলজি - বাত ও বাতজ্বর সংক্রান্ত'
    'Transfusion Medicine':'ট্রান্সফিউশন মেডিসিন - রক্ত পরিসঞ্চালন সংক্রান্ত'
    'Cardiac Surgery':'কার্ডিয়াক সার্জারী'
    'Community Ophthalmology':'কমিউনিটি অপথ্যালমোলজি - চক্ষু সংক্রান্ত'
    'Neuro Surgery':'নিউরো সার্জারী - স্নায়ু বিষয়ক অপারেশন'
    'Neuro-Surgery':'নিউরো সার্জারী - স্নায়ু বিষয়ক অপারেশন'
    'Obstetrics & Gynecology':'অবস্টেট্রিকস এবং গাইনিকোলজি - ধাত্রী ও স্ত্রীবিদ্যা'
    'Ophthalmology':'অপথ্যালমোলজি - চক্ষু সংক্রান্ত'
    'Orthopedic Surgery':'অর্থোপেডিক সার্জারী - হাড় জোড় বিশেষজ্ঞ'
    'Orthopaedic Surgery':'অর্থোপেডিক সার্জারী - হাড় জোড় বিশেষজ্ঞ'
    'Otolaryngology':'অটোল্যারিংগোলজি - নাক কান ও গলা বিশেষজ্ঞ'
    'Paediatric Surgery':'পেডিয়াট্রিক সার্জারী - শিশু সার্জারী'
    'Surgery':'সার্জারী'
    'Urology':'ইউরোলজি - কিডনি যৌনাঙ্গ বিষয়ক সার্জারী'
    'Vascular Surgery':'ভাস্কুলার সার্জারী - রক্তনালী বিষয়ক সার্জারী'
    'Conservative Dentistry & Endodontics':'কনসারভেটিভ ডেন্টিস্ট্রি ও এন্ডোডন্টিক্'
    'Oral & Maxillofacial Surgery':'ওরাল এন্ড ম্যাক্সিলোফেসিয়াল সার্জারী - দন্ত ও মুখগহ্বর সার্জারী'
    'Orthodontics':'অর্থোডন্টিকস্'
    'Prosthodontics':'প্রস্থোডনটিকস্'
    'Paediatric Neurology':'শিশু স্নায়ুরোগ'
    'Pedodontics':'পেডোডন্টিক্স'
    'Respiratory Medicine':'রেসপিরেটরি মেডিসিন - শ্বাসতন্ত্ বিষয়ক'
    'Palliative Care Medicine':'পালিয়াটিভ কেয়ার মেডিসিন - উপশমমূলক মেডিসিন'
    'Paediatric Cardiology':'পেডিয়াট্রিক কার্ডিওলজি - শিশু কার্ডিওলজি'
    'Hepatobiliary, Pancreatic and Liver Transplantatio...':'হেপাটোবিলিয়ারি, পেনক্রিয়েটিক ও লিভার ট্রান্সপ্লান্ট সার্জারি'
    'Colorectal Surgery':'কলোরেক্টাল সার্জারি - বৃহদান্ত্ ও পায়ুপথের সার্জারি'
    'Reproductive Endocrinology and Infertility':'প্রজনন এন্ডোক্রিনোলজি এবং প্রজনন'
    'Fetomaternal Medicine':'ফিটোম্যাটার্নাল মেডিসিন - ভ্রূণ সংক্রান্ত মেডিসিন'
    'Gynecological Oncology':'গাইনোকলোজিক্যাল অনকোলজি - স্ত্রী বিষয়ক ক্যান্সার  সংক্রান্ত'
    'Please Provide Your Booking Information': 'দয়া করে আপনার বুকিং তথ্য প্রদান করুন'
    'Your Name': 'আপনার নাম'
    'Member Name is Required!': 'নাম আবশ্যক!'
    'Date of Birth is Required!': 'জন্ম তারিখ আবশ্যক!'
    'Date of Birth (mm/dd/yyyy)': 'জন্ম তারিখ (মাস/দিন/বছর)'
    'Gender': 'লিঙ্গ'
    'Male': 'পুরুষ'
    'Female': 'মহিলা'
    'Other': 'অন্যান্য'
    'Your Phone Number': 'ফোন নম্বর'
    'Phone Number Required. i.e.: 01712345678 or 01712345678-12': 'ফোন নম্বর আবশ্যক, যেমন ০১৭১২৩৪৫৬৭৮ অথবা ০১৭১২৩৪৫৬৭৮-১২'
    'Done': 'সম্পন্ন'
    'Book This Doctor': 'বুকিং দিন'
    'Duration': 'স্থিতিকাল'
    'Custom': 'কাস্টম'
    'Drop': 'ড্রপ'
    'Out patient/ Discharged with advice': 'বহির্বিভাগ ছাড়পত্র'
    'Out patient/ Advised admission': 'বহির্বিভাগের রোগীর ভর্তির উপদেশ'
    'Seen in emergency/ Discharged with advice': 'জরুরী রোগীর ছাড়পত্র'
    'Seen in emergency/ Advised admission': 'জরুরী রোগীর ভর্তির উপদেশ'
    '1+1+1':'১টা করে দিনে ৩ বার'
    '1+0+1':'১টা করে সকাল এবং রাতে'
    '0+0+1':'১টা করে রাতে'
    '1+0+0':'১টা করে সকালে'
    '1+1+1+1':'১টা করে দিনে ৪ বার'
    '2+2+2':'২টা করে দিনে ৩ বার'
    '2+0+2':'২টা করে সকাল এবং রাতে'
    '0+0+2':'২টা করে রাতে'
    '2+0+0':'২টা করে সকালে'
    '1/2+1/2+1/2':'১/২ (অর্ধেক) করে দিনে ৩ বার'
    '1/2+0+1/2':'১/২ (অর্ধেক) করে সকাল এবং রাতে'
    '0+0+1/2':'১/২ (অর্ধেক) করে রাতে'
    '1/2+0+0':'১/২ (অর্ধেক) করে সকালে'
    '1/4+1/4+1/4':'১/৪ (৪ ভাগের ১ ভাগ) দিনে ৩ বার'
    '1/4+0+1/4':'১/৪ (৪ ভাগের ১ ভাগ) করে সকাল এবং রাতে'
    '0+0+1/4':'১/৪ (৪ ভাগের ১ ভাগ) করে রাতে'
    '1/4+0+0':'১/৪ (৪ ভাগের ১ ভাগ) করে সকালে'
    '1/4+1/4+1/4+1/4':'১/৪ (৪ ভাগের ১ ভাগ) করে দিনে ৪ বার'
    '1 Capsule Four Times Daily':'১টা করে ক্যাপসুল দিনে ৪ বার'
    '1 Capsule Three Times Daily':'১টা করে ক্যাপসুল দিনে ৩ বার'
    '1 Capsule Two Times Daily':'১টা করে ক্যাপসুল দিনে ২ বার'
    '1 Capsule One Time Daily In The Morning':'১টা করে ক্যাপসুল দিনে ১ বার সকালে'
    '1 Capsule One Time Daily At Night':'১টা করে ক্যাপসুল দিনে ১ বার রাতে'
    '1 Drop Four Times Daily':'১ ড্রপ দিনে ৪ বার'
    '1 Drop Three Times Daily':'১ ড্রপ দিনে ৩ বার'
    '1 Drop Two Times Daily':'১ ড্রপ দিনে ২ বার'
    '1 Drop One Time Daily In The Morning':'১ ড্রপ দিনে দিনে ১ বার সকালে'
    '1 Drop One Time Daily At Night':'১ ড্রপ দিনে ১ বার রাতে'
    '1 Injection Four Times Daily':'১টা করে ইনজেকশন দিনে ৪ বার'
    '1 Injection Three Times Daily':'১টা করে ইনজেকশন দিনে ৩ বার'
    '1 Injection Two Times Daily':'১টা করে ইনজেকশন দিনে ২ বার'
    '1 Injection One Time Daily In The Morning':'১টা করে ইনজেকশন দিনে ১ বার সকালে'
    '1 Injection One Time Daily At Night':'১টা করে ইনজেকশন দিনে ১ বার রাতে'
    '1 Tablet Four Times Daily':'১টা করে ট্যাবলেট দিনে ৪ বার'
    '1 Tablet Three Times Daily':'১টা করে ট্যাবলেট দিনে ৩ বার'
    '1 Tablet Two Times Daily':'১টা করে ট্যাবলেট দিনে ২ বার'
    '1 Tablet One Time Daily In The Morning':'১টা করে ট্যাবলেট দিনে ১ বার সকালে'
    '1 Tablet One Time Daily At Night':'১টা করে ট্যাবলেট দিনে ১ বার রাতে'
    '2 Capsules Four Times Daily':'২টা করে ক্যাপসুল দিনে ৪ বার'
    '2 Capsules Three Times Daily':'২টা করে ক্যাপসুল দিনে ৩ বার'
    '2 Capsules Two Times Daily':'২টা করে ক্যাপসুল দিনে ২ বার'
    '2 Capsules One Time Daily In The Morning':'২টা করে ক্যাপসুল দিনে ১ বার সকালে'
    '2 Capsules One Time Daily At Night':'২টা করে ক্যাপসুল দিনে ১ বার রাতে'
    '2 Drops Four Times Daily':'২ ড্রপ দিনে ৪ বার'
    '2 Drops Three Times Daily':'২ ড্রপ দিনে ৩ বার'
    '2 Drops Two Times Daily':'২ ড্রপ দিনে ২ বার'
    '2 Drops One Time Daily In The Morning':'২ ড্রপ দিনে দিনে ১ বার সকালে'
    '2 Drops One Time Daily At Night':'২ ড্রপ দিনে ১ বার রাতে'
    '2 Injections Four Times Daily':'২টা করে ইনজেকশন দিনে ৪ বার'
    '2 Injections Three Times Daily':'২টা করে ইনজেকশন দিনে ৩ বার'
    '2 Injections Two Times Daily':'২টা করে ইনজেকশন দিনে ২ বার'
    '2 Injections One Time Daily In The Morning':'২টা করে ইনজেকশন দিনে ১ বার সকালে'
    '2 Injections One Time Daily At Night':'২টা করে ইনজেকশন দিনে ১ বার রাতে'
    '2 Tablets Four Times Daily':'২টা করে ট্যাবলেট দিনে ৪ বার'
    '2 Tablets Three Times Daily':'২টা করে ট্যাবলেট দিনে ৩ বার'
    '2 Tablets Two Times Daily':'২টা করে ট্যাবলেট দিনে ২ বার'
    '2 Tablets One Time Daily In The Morning':'২টা করে ট্যাবলেট দিনে ১ বার সকালে'
    '2 Tablets One Time Daily At Night':'২টা করে ট্যাবলেট দিনে ১ বার রাতে'
    '1/2 Capsule Four Times Daily':'১/২ (অর্ধেক) ক্যাপসুল দিনে ৪ বার'
    '1/2 Capsule Three Times Daily':'১/২ (অর্ধেক) ক্যাপসুল দিনে ৩ বার'
    '1/2 Capsule Two Times Daily':'১/২ (অর্ধেক) ক্যাপসুল দিনে ২ বার'
    '1/2 Capsule One Time Daily In The Morning':'১/২ (অর্ধেক) ক্যাপসুল দিনে ১ বার সকালে'
    '1/2 Capsule One Time Daily At Night':'১/২ (অর্ধেক) ক্যাপসুল দিনে ১ বার রাতে'
    '1/2 Drop Four Times Daily':'১/২ ড্রপ দিনে ৪ বার'
    '1/2 Drop Three Times Daily':'১/২ ড্রপ দিনে ৩ বার'
    '1/2 Drop Two Times Daily':'১/২ ড্রপ দিনে ২ বার'
    '1/2 Drop One Time Daily In The Morning':'১/২ ড্রপ দিনে দিনে ১ বার সকালে'
    '1/2 Drop One Time Daily At Night':'১/২ ড্রপ দিনে ১ বার রাতে'
    '1/2 Injection Four Times Daily':'১/২ (অর্ধেক) ইনজেকশন দিনে ৪ বার'
    '1/2 Injection Three Times Daily':'১/২ (অর্ধেক) ইনজেকশন দিনে ৩ বার'
    '1/2 Injection Two Times Daily':'১/২ (অর্ধেক) ইনজেকশন দিনে ২ বার'
    '1/2 Injection One Time Daily In The Morning':'১/২ (অর্ধেক) ইনজেকশন দিনে ১ বার সকালে'
    '1/2 Injection One Time Daily At Night':'১/২ (অর্ধেক) ইনজেকশন দিনে ১ বার রাতে'
    '1/2 Tablet Four Times Daily':'১/২ (অর্ধেক) ট্যাবলেট দিনে ৪ বার'
    '1/2 Tablet Three Times Daily':'১/২ (অর্ধেক) ট্যাবলেট দিনে ৩ বার'
    '1/2 Tablet Two Times Daily':'১/২ (অর্ধেক) ট্যাবলেট দিনে ২ বার'
    '1/2 Tablet One Time Daily In The Morning':'১/২ (অর্ধেক) ট্যাবলেট দিনে ১ বার সকালে'
    '1/2 Tablet One Time Daily At Night':'১/২ (অর্ধেক) ট্যাবলেট দিনে ১ বার রাতে'
    '1/4 Capsule Four Times Daily':'১/৪ (৪ ভাগের ১ ভাগ) ক্যাপসুল দিনে ৪ বার'
    '1/4 Capsule Three Times Daily':'১/৪ (৪ ভাগের ১ ভাগ) ক্যাপসুল দিনে ৩ বার'
    '1/4 Capsule Two Times Daily':'১/৪ (৪ ভাগের ১ ভাগ) ক্যাপসুল দিনে ২ বার'
    '1/4 Capsule One Time Daily In The Morning':'১/৪ (৪ ভাগের ১ ভাগ) ক্যাপসুল দিনে ১ বার সকালে'
    '1/4 Capsule One Time Daily At Night':'১/৪ (৪ ভাগের ১ ভাগ) ক্যাপসুল দিনে ১ বার রাতে'
    '1/4 Drop Four Times Daily':'১/৪ (৪ ভাগের ১ ভাগ) ড্রপ দিনে ৪ বার'
    '1/4 Drop Three Times Daily':'১/৪ (৪ ভাগের ১ ভাগ) ড্রপ দিনে ৩ বার'
    '1/4 Drop Two Times Daily':'১/৪ (৪ ভাগের ১ ভাগ) ড্রপ দিনে ২ বার'
    '1/4 Drop One Time Daily In The Morning':'১/৪ (৪ ভাগের ১ ভাগ) ড্রপ দিনে দিনে ১ বার সকালে'
    '1/4 Drop One Time Daily At Night':'১/৪ (৪ ভাগের ১ ভাগ) ড্রপ দিনে ১ বার রাতে'
    '1/4 Injection Four Times Daily':'১/৪ (৪ ভাগের ১ ভাগ) ইনজেকশন দিনে ৪ বার'
    '1/4 Injection Three Times Daily':'১/৪ (৪ ভাগের ১ ভাগ) ইনজেকশন দিনে ৩ বার'
    '1/4 Injection Two Times Daily':'১/৪ (৪ ভাগের ১ ভাগ) ইনজেকশন দিনে ২ বার'
    '1/4 Injection One Time Daily In The Morning':'১/৪ (৪ ভাগের ১ ভাগ) ইনজেকশন দিনে ১ বার সকালে'
    '1/4 Injection One Time Daily At Night':'১/৪ (৪ ভাগের ১ ভাগ) ইনজেকশন দিনে ১ বার রাতে'
    '1/4 Tablet Four Times Daily':'১/৪ (৪ ভাগের ১ ভাগ) ট্যাবলেট দিনে ৪ বার'
    '1/4 Tablet Three Times Daily':'১/৪ (৪ ভাগের ১ ভাগ) ট্যাবলেট দিনে ৩ বার'
    '1/4 Tablet Two Times Daily':'১/৪ (৪ ভাগের ১ ভাগ) ট্যাবলেট দিনে ২ বার'
    '1/4 Tablet One Time Daily In The Morning':'১/৪ (৪ ভাগের ১ ভাগ) ট্যাবলেট দিনে ১ বার সকালে'
    '1/4 Tablet One Time Daily At Night':'১/৪ (৪ ভাগের ১ ভাগ) ট্যাবলেট দিনে ১ বার রাতে'
    'Quick info':'রোগীর তথ্য দেখুন'
    'Registerd Phone Number' : 'নিবন্ধিত ফোন নম্বর'
    'Record': 'রেকর্ড'
    'Created Date': 'প্রস্তুতের তারিখ'
    'Created By': 'প্রস্তুত করেছেন'
    'Edit Patient' :'রোগীর তথ্য সম্পাদন করুন'
    'Patient Id' : 'রোগীর আইডি'
    'Instruction' : 'নির্দেশাবলী'
    'Confirm Diagnosis (Previous)':'অতীতে নির্ণীত রোগ'
    'Current operation performed':'চলতি অপারেশন '
    'Medicine':'ঔষধ সমূহ'
    'Visits & Report':' সাক্ষাৎ ও রিপোর্ট সমূহ'
    'Current diagnosis & precedures':'চলতি রোগ ও চিকিৎসা সমূহ'
    'Previous operation performed':'অতীত শল্যচিকিত্সা সমূহ'
    'Test Results':'ফলাফল (পরীক্ষা)'
    'Doctor Patient Notes':'চিকিৎসক রোগীর নথি'
    'Activity Log':'একটিভিটি লগ'
    'Patient Current Medicine':'রোগীর বর্তমান ঔষধ'
    'New Medicine':'নতুন ঔষধ'
    'Favorite(s)':'পছন্দসমুহ'
    'Insulin':'ইন্সুলিন'
    'Add Medicine':'ঔষধ যোগ করুন'
    '1 Day': '১ দিন'
    '2 Days':'২ দিন'
    '3 Days':'৩ দিন'
    '4 Days':'৪ দিন'
    '5 Days':'৫ দিন'
    '6 Days':'৬ দিন'
    '7 Days':'৭ দিন'
    '8 Days':'৮ দিন'
    '9 Days':'৯ দিন'
    '10 Days':'১০ দিন'
    '11 Days':'১১ দিন'
    '12 Days':'১২ দিন'
    '13 Days':'১৩ দিন'
    '14 Days':'১৪ দিন'
    '15 Days':'১৫ দিন'
    '16 Days':'১৬ দিন'
    '17 Days':'১৭ দিন'
    '18 Days':'১৮ দিন'
    '19 Days':'১৯ দিন'
    '20 Days':'২০ দিন'
    '21 Days':'২১ দিন'
    '22 Days':'২২ দিন'
    '23 Days':'২৩ দিন'
    '24 Days':'২৪ দিন'
    '25 Days':'২৫ দিন'
    '26 Days':'২৬ দিন'
    '27 Days':'২৭ দিন'
    '28 Days':'২৮ দিন'
    '29 Days':'২৯ দিন'
    '30 Days':'৩০ দিন'
    '1 Week':'১ সপ্তাহ'
    '2 Weeks':'২ সপ্তাহ'
    '3 Weeks':'৩ সপ্তাহ'
    '4 Weeks':'৪ সপ্তাহ'
    '5 Weeks':'৫ সপ্তাহ'
    '6 Weeks':'৬ সপ্তাহ'
    '7 Weeks':'৭ সপ্তাহ'
    '8 Weeks':'৮ সপ্তাহ'
    '1 Month':'১ মাস'
    '2 Months':'২ মাস'
    '3 Months':'৩ মাস'
    '4 Months':'৪ মাস'
    '5 Months':'৫ মাস'
    '6 Months':'৬ মাস'
    '7 Months':'৭ মাস'
    '8 Months':'৮ মাস'
    '9 Months':'৯ মাস'
    '10 Months':'১০ মাস'
    '11 Months':'১১ মাস'
    '12 Months':'১২ মাস'




    


app.lang.numerals = 
  'bn-bd':
    '0':'০'
    '1':'১'
    '2':'২'
    '3':'৩'
    '4':'৪'
    '5':'৫'
    '6':'৬'
    '7':'৭'
    '8':'৮'
    '9':'৯'
    '.':'.'
    '+':'+'
    '1+1+1':'১+১+১'
    '1+0+1':'১+০+১'
    '0+0+1':'০+০+১'
    '1+0+0':'১+০+০'
    '1+1+1+1':'১+১+১+১'
    '2+2+2':'২+২+২'
    '2+0+2':'২+০+২'
    '0+0+2':'০+০+২'
    '2+0+0':'২+০+০'
    '1/2+1/2+1/2':'১/২+১/২+১/২'
    '1/2+0+1/2':'১/২+০+১/২'
    '0+0+1/2':'০+০+১/২'
    '1/2+0+0':'১/২+০+০'
    '1/4+1/4+1/4':'১/৪+১/৪+১/৪'
    '1/4+0+1/4':'১/৪+০+১/৪'
    '0+0+1/4':'০+০+১/৪'
    '1/4+0+0':'১/৪+০+০'
    '1/4+1/4+1/4+1/4':'১/৪+১/৪+১/৪+১/৪'

app.lang.date = 
  'bn-bd':
    'January':'জানুয়ারি'
    'February': 'ফেব্রুয়ারি'
    'March':'মার্চ'
    'April': 'এপ্রিল'
    'May': 'মে'
    'June': 'জুন'
    'July': 'জুলাই'
    'August': 'আগস্ট'
    'September': 'সেপ্টেম্বর'
    'October': 'অক্টোবর'
    'November': 'নভেম্বর'
    'December': 'ডিসেম্বর'
    'Jan': 'জানু'
    'Feb': 'ফেব্রু'
    'Mar': 'মার্চ'
    'Apr': 'এপ্রি'
    'May': 'মে'
    'Jun': 'জুন'
    'Jul': 'জুল'
    'Aug': 'আগ'
    'Sep': 'সেপ্টে'
    'Oct': 'অক্টো'
    'Nov': 'নভে'
    'Dec': 'ডিসে'
    'Sunday': 'রবিবার'
    'Monday': 'সোমবার'
    'Tuesday': 'মঙ্গলবার'
    'Wednesday': 'বুধবার'
    'Thursday': 'বৃহস্পতিবার'
    'Friday': 'শুক্রবার'
    'Saturday': 'শনিবার'
    'Sun': 'রবি'
    'Mon': 'সোম'
    'Tue': 'মঙ্গল'
    'Wed': 'বুধ'
    'Thu': 'বৃহঃ'
    'Fri': 'শুক্র'
    'Sat': 'শনি'



app.lang.translatePhrase = (phraseIdentifier, languageIdentifier)->
  if languageIdentifier of app.lang.phrases
    map = app.lang.phrases[languageIdentifier]
    return map[phraseIdentifier] if phraseIdentifier of map
  return phraseIdentifier

app.lang.translateNumeral = (numeral, languageIdentifier)->
  if languageIdentifier of app.lang.numerals
    map = app.lang.numerals[languageIdentifier]
    numeral = (''+numeral).split ''
    newNumeral = []
    for digit in numeral
      unless digit of map
        return 'TRANSLATION_FAILED FOR "' + digit + '"'
      newNumeral.push map[digit]
    return (newNumeral.join '')
  return (''+numeral)

